apiVersion: v1
kind: Service
metadata:
  name: antiadhd-postgres
  labels:
    app.kubernetes.io/name: antiadhd-postgres
    app.kubernetes.io/part-of: antiadhd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: antiadhd-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
