apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: antiadhd-postgres-backups
  labels:
    app.kubernetes.io/name: antiadhd-postgres
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: antiadhd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
