CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(120) NOT NULL,
    name VARCHAR(80) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(60) NOT NULL,
    color VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_categories_user ON categories (user_id);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(40) NOT NULL,
    color VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tags_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_tags_user ON tags (user_id);

CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    start_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    end_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    color VARCHAR(20) NOT NULL,
    repeat_type VARCHAR(20) NOT NULL,
    completed BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_schedules_repeat_type
        CHECK (repeat_type IN ('NONE', 'DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT fk_schedules_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_schedules_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_schedules_user_start ON schedules (user_id, start_at);
CREATE INDEX idx_schedules_user_end ON schedules (user_id, end_at);

CREATE TABLE schedule_tags (
    schedule_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (schedule_id, tag_id),
    CONSTRAINT fk_schedule_tags_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (id),
    CONSTRAINT fk_schedule_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id)
);

CREATE TABLE focus_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    planned_minutes INTEGER,
    started_at TIMESTAMP(6) WITHOUT TIME ZONE,
    ended_at TIMESTAMP(6) WITHOUT TIME ZONE,
    completed BOOLEAN NOT NULL,
    note VARCHAR(1000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_focus_sessions_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_focus_sessions_user ON focus_sessions (user_id);

CREATE TABLE goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    target_date DATE,
    progress INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_goals_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_goals_user ON goals (user_id);

CREATE TABLE routines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    repeat_type VARCHAR(20) NOT NULL,
    target_time TIME(6) WITHOUT TIME ZONE,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_routines_repeat_type
        CHECK (repeat_type IN ('NONE', 'DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT fk_routines_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_routines_user ON routines (user_id);

CREATE TABLE daily_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    review_date DATE NOT NULL,
    mood VARCHAR(40),
    summary VARCHAR(1000),
    accomplishment VARCHAR(1000),
    improvement VARCHAR(1000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_daily_reviews_user_date UNIQUE (user_id, review_date),
    CONSTRAINT fk_daily_reviews_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_daily_reviews_user_date ON daily_reviews (user_id, review_date);
