CREATE TABLE inbox_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    estimated_minutes INTEGER,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_inbox_items_estimated_minutes
        CHECK (estimated_minutes IS NULL OR estimated_minutes BETWEEN 1 AND 480),
    CONSTRAINT chk_inbox_items_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_inbox_items_status CHECK (status IN ('INBOX', 'PLANNED', 'DONE')),
    CONSTRAINT fk_inbox_items_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_inbox_items_user_status_created
    ON inbox_items (user_id, status, created_at DESC);
