apiVersion: v1
kind: Secret
metadata:
  name: antiadhd-backend-secret
  namespace: antiadhd
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "antiadhd"
  SPRING_DATASOURCE_PASSWORD: "change-me"
  JWT_SECRET: "replace-with-at-least-32-characters-secret"
