apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: antiadhd-backend
  labels:
    app.kubernetes.io/name: antiadhd-backend
    app.kubernetes.io/part-of: antiadhd
spec:
  ingressClassName: traefik
  rules:
    - host: api.antiadhd.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: antiadhd-backend
                port:
                  name: http
